// AUTO-GENERATED by tools/static_analyze_libfekit.py
// libfekit.so version: 9.2.90
// Do NOT edit by hand. Re-run the script to refresh.
#pragma once
#include <cstdint>

namespace shamrock::offsets::v9290 {

// JNI_OnLoad VA
constexpr uintptr_t kJniOnLoad = 0x872bcUL;

// 关键字符串 VA
constexpr uintptr_t kStr_getSign                = 0x65f6f1UL;
constexpr uintptr_t kStr_requestToken           = 0x65fdc9UL;
constexpr uintptr_t kStr_proc_self_maps         = 0x6634adUL;
constexpr uintptr_t kStr_lsposed                = 0x847db2UL;
constexpr uintptr_t kStr_frida                  = 0x6634a7UL;
constexpr uintptr_t kStr_magisk                 = 0x6635e6UL;

// RegisterNatives 调用点（VA）
constexpr int kRegisterNativesCount = 8;
constexpr uintptr_t kRegisterNativesCallsites[8] = {
    0x87f6cUL,
    0x88b40UL,
    0x89750UL,
    0x8a664UL,
    0x8bb94UL,
    0x93520UL,
    0x96b80UL,
    0x9aa2cUL,
};

// 检测探针候选函数（基于 /proc/self/maps、lsposed、xposed、frida、magisk 的 xref）
// 这些函数有非常高的概率是 QQ 的反 Xposed 探针。Native hook 时只需要
// 让它们恒返 0/false 即可绕过。
constexpr int kDetectionProbeCount = 2;
constexpr uintptr_t kDetectionProbeOffsets[2] = {
    0x3293a4UL,  // proc_self_maps@0x329690
    0x2c1cf0UL,  // magisk@0x2c1cf4
};

// getSign 注册 (JNI_OnLoad 内 RegisterNatives 调用)
constexpr int kSignNativeTableCandidateCount = 4;
constexpr uintptr_t kSignNativeTableCandidates[4] = {
    0x87f6cUL,
    0x88b40UL,
    0x89750UL,
    0x8a664UL,
};

} // namespace shamrock::offsets::v9290
