// AUTO-GENERATED by tools/run_analyze_930.py
// libfekit.so version: 9.3.0
// NOTE: 0x2b017c (ro.debuggable) 曾导致联网异常，暂不 hook；仅保留 maps + magisk。
#pragma once
#include <cstdint>

namespace shamrock::offsets::v9300 {
constexpr uintptr_t kJniOnLoad = 0x86f00UL;

constexpr int kDetectionProbeCount = 2;
constexpr uintptr_t kDetectionProbeOffsets[2] = {
    0x338210UL,  // proc_self_maps@0x338214
    0x2bd3c0UL,  // magisk@0x2bd3c0
};
} // namespace shamrock::offsets::v9300
